apiVersion: v1
kind: Service
metadata:
  name: movie-catalog-service
  namespace: default
  labels:
    app: movie-catalog-service
spec:
  ports:
    -
      port: 8081
      targetPort: 8081
      protocol: TCP
      nodePort: 30002
  selector:
    app: movie-catalog
  type: NodePort